### ISSUE TITLE
Storing configuration in Setting.h in a better way

### ISSUE THREAD

**Issue by drewish** [kylebrowning/drupal-ios-sdk#45]
My preferred way of using this library is by checking it out as a git submodule. The problem is that since the Settings.h file is stored in the sub-repo and also included by code in the sub-repo. This sort of tangles things up meaning I ether have to commit my API settings to the sub-repo or just copy all the DIOS files in into my project. I'm guessing you do the later. 

I feel like there's got to be a cleaner way to store the API configuration. Perhaps in a .plist file? Maybe stored in the DIOSSession singleton? If it's not hardcoded in file you could do things like change server configuration in response to a UI control changing (say flipping over to a devel server).

Thoughts? You open to this type of a change?

**Comment by kylebrowning** [comment]
I guess my issue with NOT providing a Settings file is that there needs to be pretty clear documentation on how to get connected and I wanted the smallest barrier to entry because Drupal and Services are already pretty complex.

Id be open to this sort of and dumping things into a plist file that you create. As long as we supply an example and clear documentation.

**Comment by shunting** [comment]
An example and clear documentation would be great, and would greatly reduce barriers to entry.

**Comment by kylebrowning** [comment]
Fixed now. 

There is no longer a requirement for Settings.h and it has been removed. New digs version ill be 2.1.0 when released, but you can checkout from master now.
0f3c747e45a221ccde4ac43b2fcb37c4bf59737d
76d755d11477bfa1aab3d9fb6f8cb95bf9034782
